name: onedrive-client
base: core22
version: "2.4.23"
summary: A free Microsoft OneDrive Client
description: |
  This powerful and highly configurable client can run on all major  
  Linux distributions, FreeBSD, or as a Docker container. It supports 
  one-way and two-way sync capabilities and securely connects to 
  Microsoft OneDrive services.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  onedrive:
    command: /usr/local/bin/onedrive
    plugs: [home]

parts:
  onedrive:
    plugin: autotools
    source: https://github.com/abraunegg/onedrive.git
    source-type: git
    build-packages:
      - build-essential
      - libcurl4-openssl-dev
      - libsqlite3-dev
      - libnotify-dev
      - make
      - pkg-config
    build-snaps:
      - dmd
    stage-packages:
      - libcurl4
