name: onedrive
base: core22
version: "2.4.23"
summary: A free Microsoft OneDrive Client
description: |
  This powerful and highly configurable client can run on all major  
  Linux distributions, FreeBSD, or as a Docker container. It supports 
  one-way and two-way sync capabilities and securely connects to 
  Microsoft OneDrive services.
website: https://abraunegg.github.io/

grade: stable
confinement: strict

apps:
  onedrive:
    command: /usr/local/bin/onedrive
    plugs: [home, network]

parts:
  onedrive:
    plugin: autotools
    source: https://github.com/abraunegg/onedrive.git
    source-type: git
    build-packages:
      - build-essential
      - libcurl4-openssl-dev
      - libsqlite3-dev
      - libnotify-dev
      - make
      - pkg-config
    build-snaps:
      - dmd
    stage-packages:
      - libcurl4

